config/routes.rb
UiPlayground::Application.routes.draw do
  get "animations/index"

  get "animations/basic"

  get "welcome/index"

  root :to => 'welcome#index'

end

app/controllers/animations_controller.rb
class AnimationsController < ApplicationController
  def index
  end

  def basic
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

end

app/helpers/animations_helper.rb
module AnimationsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/animations/basic.html.erb
<h1 style="text-align: center;">Basic animation</h1>

<div>
  <div class="control-panel" style="clear: right;">
    <button class="trigger" id="basic-trigger">Click me to start animating</button>
  </div>
  <div class="dancer" style="width: 100px; height: 100px; position: absolute; background-color: red;"></div>
  <div class="dancer" style="width: 100px; height: 100px; position: absolute; background-color: orange;"></div>
  <div class="dancer" style="width: 100px; height: 100px; position: absolute; background-color: yellow;"></div>
  <div class="dancer" style="width: 100px; height: 100px; position: absolute; background-color: green;"></div>
  <div class="dancer" style="width: 100px; height: 100px; position: absolute; background-color: blue;"></div>
  <div class="dancer" style="width: 100px; height: 100px; position: absolute; background-color: violet;"></div>
  <div class="dancer" style="width: 100px; height: 100px; position: absolute; background-color: pink;"></div>
</div>

app/views/animations/index.html.erb
<h1>Animations</h1>

<ul>
  <li><%= link_to 'Basic animations', animations_basic_path %></li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>UiPlayground</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<h1>This is an application that I use to play around with visual elements</h1>

<ul>
  <li><%= link_to 'Animations', animations_index_path %></li>
</ul>